"""Initial migration

Revision ID: 2608d658dbcb
Revises: 
Create Date: 2026-06-04 23:49:55.233460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import backend

# revision identifiers, used by Alembic.
revision: str = '2608d658dbcb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_registry',
    sa.Column('workspace_id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('PERSON', 'SERVICE', 'REPOSITORY', 'TICKET', 'DECISION', 'DOCUMENT', 'TEAM', name='entitytype'), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('graph_sync_status', sa.Enum('PENDING', 'SYNCED', 'FAILED', name='syncstatus'), nullable=False),
    sa.Column('source_event_count', sa.Integer(), nullable=False),
    sa.Column('id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'entity_type', 'canonical_name', name='uq_entity_registry_workspace_type_name')
    )
    op.create_index(op.f('ix_entity_registry_graph_sync_status'), 'entity_registry', ['graph_sync_status'], unique=False)
    op.create_index(op.f('ix_entity_registry_id'), 'entity_registry', ['id'], unique=False)
    op.create_index(op.f('ix_entity_registry_workspace_id'), 'entity_registry', ['workspace_id'], unique=False)
    op.create_table('events',
    sa.Column('workspace_id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('source', sa.Enum('SLACK', 'GITHUB', 'JIRA', 'NOTION', 'EMAIL', name='sourcetype'), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('author_id', sa.String(length=255), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_status', sa.Enum('PENDING', 'EMBEDDED', 'FAILED', name='embeddingstatus'), nullable=False),
    sa.Column('id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'source', 'source_id', name='uq_events_workspace_source_id')
    )
    op.create_index(op.f('ix_events_embedding_status'), 'events', ['embedding_status'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_workspace_id'), 'events', ['workspace_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('workspace_id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('source', sa.Enum('SLACK', 'GITHUB', 'JIRA', 'NOTION', 'EMAIL', name='sourcetype'), nullable=False),
    sa.Column('source_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ingestionstatus'), nullable=False),
    sa.Column('events_ingested', sa.Integer(), nullable=False),
    sa.Column('events_failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_id'), 'ingestion_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_status'), 'ingestion_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_workspace_id'), 'ingestion_jobs', ['workspace_id'], unique=False)
    op.create_table('workspace_snapshots',
    sa.Column('workspace_id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('key_decisions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('last_ingestion_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_snapshots_id'), 'workspace_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_snapshots_workspace_id'), 'workspace_snapshots', ['workspace_id'], unique=True)
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_workspace_snapshots_workspace_id'), table_name='workspace_snapshots')
    op.drop_index(op.f('ix_workspace_snapshots_id'), table_name='workspace_snapshots')
    op.drop_table('workspace_snapshots')
    op.drop_index(op.f('ix_ingestion_jobs_workspace_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_status'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_events_workspace_id'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_embedding_status'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_entity_registry_workspace_id'), table_name='entity_registry')
    op.drop_index(op.f('ix_entity_registry_id'), table_name='entity_registry')
    op.drop_index(op.f('ix_entity_registry_graph_sync_status'), table_name='entity_registry')
    op.drop_table('entity_registry')
    # ### end Alembic commands ###
