"""phase5_config_registry

Revision ID: f80f6fdc088a
Revises: b2c3d4e5f6a7

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import backend.db.models.base

# revision identifiers, used by Alembic.
revision: str = 'f80f6fdc088a'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_registry_version',
    sa.Column('workspace_id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', backend.db.models.base.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_registry_version_id'), 'config_registry_version', ['id'], unique=False)
    op.create_index(op.f('ix_config_registry_version_workspace_id'), 'config_registry_version', ['workspace_id'], unique=True)
    op.create_table('config_services',
    sa.Column('workspace_id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_config_services_workspace_name')
    )
    op.create_index(op.f('ix_config_services_id'), 'config_services', ['id'], unique=False)
    op.create_index(op.f('ix_config_services_workspace_id'), 'config_services', ['workspace_id'], unique=False)
    op.create_table('config_teams',
    sa.Column('workspace_id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_config_teams_workspace_name')
    )
    op.create_index(op.f('ix_config_teams_id'), 'config_teams', ['id'], unique=False)
    op.create_index(op.f('ix_config_teams_workspace_id'), 'config_teams', ['workspace_id'], unique=False)
    op.create_table('config_dependencies',
    sa.Column('service_id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('depends_on_service_id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('workspace_id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_service_id'], ['config_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['config_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'depends_on_service_id')
    )
    op.create_index(op.f('ix_config_dependencies_workspace_id'), 'config_dependencies', ['workspace_id'], unique=False)
    op.create_table('config_ownership',
    sa.Column('team_id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('service_id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('workspace_id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['config_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['config_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'service_id')
    )
    op.create_index(op.f('ix_config_ownership_workspace_id'), 'config_ownership', ['workspace_id'], unique=False)
    op.create_table('config_repositories',
    sa.Column('workspace_id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('repo_url', sa.String(length=1024), nullable=False),
    sa.Column('service_id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('id', backend.db.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['config_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'repo_url', name='uq_config_repos_workspace_url')
    )
    op.create_index(op.f('ix_config_repositories_id'), 'config_repositories', ['id'], unique=False)
    op.create_index(op.f('ix_config_repositories_workspace_id'), 'config_repositories', ['workspace_id'], unique=False)
    # (Removed spurious event_embeddings/memory_objects alters)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # (Removed spurious event_embeddings/memory_objects alters)
    op.drop_index(op.f('ix_config_repositories_workspace_id'), table_name='config_repositories')
    op.drop_index(op.f('ix_config_repositories_id'), table_name='config_repositories')
    op.drop_table('config_repositories')
    op.drop_index(op.f('ix_config_ownership_workspace_id'), table_name='config_ownership')
    op.drop_table('config_ownership')
    op.drop_index(op.f('ix_config_dependencies_workspace_id'), table_name='config_dependencies')
    op.drop_table('config_dependencies')
    op.drop_index(op.f('ix_config_teams_workspace_id'), table_name='config_teams')
    op.drop_index(op.f('ix_config_teams_id'), table_name='config_teams')
    op.drop_table('config_teams')
    op.drop_index(op.f('ix_config_services_workspace_id'), table_name='config_services')
    op.drop_index(op.f('ix_config_services_id'), table_name='config_services')
    op.drop_table('config_services')
    op.drop_index(op.f('ix_config_registry_version_workspace_id'), table_name='config_registry_version')
    op.drop_index(op.f('ix_config_registry_version_id'), table_name='config_registry_version')
    op.drop_table('config_registry_version')
    # ### end Alembic commands ###
